
all: home user user-stem

home : home.c
	gcc -o home home.c

user : user.c
	gcc -o user user.c

user-stem : user-stem.c
	gcc -o user-stem user-stem.c


.PHONY: clean
clean:
	rm -f home user user-stem
